name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a bit
              run: echo "hello buddy"
            - name: multiline
              run: |
                node -v
                npm -v
    dependajob:
        runs-on: ubuntu-latest
        needs: run-shell-commands
        steps:
            - name: some_echo
              run: echo "so fasttt"
            - name: errrrror step
              run: nocommandhere